services:
    App\Twitter\Infrastructure\Healthcheck\Controller\HealthcheckController:
        public: true
        class: 'App\Twitter\Infrastructure\Healthcheck\Controller\HealthcheckController'
        arguments:
            - '%allowed.origin%'
            - '%kernel.environment%'

    App\Trends\Infrastructure\Controller\TrendsController:
        public: true
        class: 'App\Trends\Infrastructure\Controller\TrendsController'
        arguments:
            - '%allowed.origin%'
            - '%kernel.environment%'
        properties:
            logger:                         '@logger'
            redisCache:                     '@app.cache.redis'
            popularPublicationRepository:   '@App\Trends\Infrastructure\Repository\PopularPublicationRepository'
