services:
    App\Twitter\Infrastructure\Repository\Membership\MemberRepository:
        class: 'App\Twitter\Infrastructure\Repository\Membership\MemberRepository'
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - 'App\Membership\Domain\Entity\Legacy\Member'
        calls:
            - [ 'setLogger', [ '@logger'] ]
        tags:
            - { name: 'doctrine.repository_service' }

    App\Twitter\Domain\Membership\Repository\MemberRepositoryInterface: '@App\Twitter\Infrastructure\Repository\Membership\MemberRepository'

    App\Trends\Infrastructure\Repository\PopularPublicationRepository:
        class: 'App\Trends\Infrastructure\Repository\PopularPublicationRepository'
        arguments:
            - '%kernel.project_dir%'
            - '@logger'
