services:
    App\Membership\Infrastructure\Repository\MemberRepository:
        class: 'App\Membership\Infrastructure\Repository\MemberRepository'
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - 'App\Membership\Domain\Entity\Member'
        calls:
            - [ 'setLogger', [ '@logger'] ]
        tags:
            - { name: 'doctrine.repository_service' }

    App\Membership\Domain\Repository\MemberRepositoryInterface: '@App\Membership\Infrastructure\Repository\MemberRepository'
