services:
    app.token_authenticator:
        class: 'App\Twitter\Infrastructure\Security\Authentication\TokenAuthenticator'
        calls:
            - [ 'setMemberRepository', [ '@App\Twitter\Infrastructure\Repository\Membership\MemberRepository' ] ]
            - [ 'setLogger', [ '@logger'] ]

    App\Twitter\Infrastructure\Security\Authentication\CachedApiKeyUserProvider:
        arguments:
            $inner:       '@security.user.provider.concrete.member_entity_provider'
            $redisCache:  '@App\Twitter\Infrastructure\Cache\RedisCache'
            $appSecret:   '%env(APP_SECRET)%'
            $ttlSeconds:  60
