# [PostgreSQL](https://hub.docker.com/layers/postgres/library/postgres/14.3-bullseye/images/sha256-5ea2da1f0275e38a6f39735b48a3688aae6ddfa2ad15971722d6fc0f2152918b?context=explore)
FROM postgres:14.3-bullseye

EXPOSE 5432

CMD ["postgres"]
