doctrine_migrations:
    migrations_paths:
        'App\Membership\Infrastructure\Database\Migrations': '%kernel.project_dir%/src/Membership/Infrastructure/Database/Migrations'
        'App\Newsletter\Infrastructure\Database\Migrations': '%kernel.project_dir%/src/Newsletter/Infrastructure/Database/Migrations'
        'App\Chat\Infrastructure\Database\Migrations': '%kernel.project_dir%/src/Chat/Infrastructure/Database/Migrations'
