security:
    providers:
        member_entity_provider:
            entity:
                class: App\Membership\Domain\Entity\Member
                property: id

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: member_entity_provider
            stateless: true
            access_token:
                token_handler: App\Security\Infrastructure\Symfony\ApiAccessTokenHandler
                token_extractors: [header]
                realm: 'revue-de-presse'

when@prod:
    security:
        access_control:
            - { path: ^/api/healthcheck,            role: PUBLIC_ACCESS }
            - { path: ^/api/token,                  role: PUBLIC_ACCESS }
            - { path: ^/api/docs,                   role: PUBLIC_ACCESS }
            - { path: ^/api/tiktok/oauth/callback,  role: PUBLIC_ACCESS }
            - { path: ^/api,                        role: ROLE_USER }

when@dev:
    security:
        access_control:
            - { path: ^/api/healthcheck,            role: PUBLIC_ACCESS }
            - { path: ^/api/token,                  role: PUBLIC_ACCESS }
            - { path: ^/api/docs,                   role: PUBLIC_ACCESS }
            - { path: ^/api/tiktok/oauth/callback,  role: PUBLIC_ACCESS }
            - { path: ^/api,                        role: ROLE_USER }

when@test:
    security:
        access_control:
            - { path: ^/api/healthcheck,            role: PUBLIC_ACCESS }
            - { path: ^/api/token,                  role: PUBLIC_ACCESS }
            - { path: ^/api/docs,                   role: PUBLIC_ACCESS }
            - { path: ^/api/tiktok/oauth/callback,  role: PUBLIC_ACCESS }
            - { path: ^/api,                        role: ROLE_USER }
