services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    App\Tests\NewsReview\Infrastructure\Repository\InMemoryPopularPublicationRepository:
        class: 'App\Tests\NewsReview\Infrastructure\Repository\InMemoryPopularPublicationRepository'

    app.cache.redis:
        class: 'App\Tests\Twitter\Infrastructure\Cache\InMemoryRedisCache'
