# logfilename                                                                              [owner:group] mode count size when flags
/Users/shal/repositories/deploying/org.revue-de-presse.api/var/llama/logs/chat.out.log    shal:staff 644  7     *    @T03 J
/Users/shal/repositories/deploying/org.revue-de-presse.api/var/llama/logs/chat.err.log    shal:staff 644  7     *    @T03 J
/Users/shal/repositories/deploying/org.revue-de-presse.api/var/llama/logs/embed.out.log   shal:staff 644  7     *    @T03 J
/Users/shal/repositories/deploying/org.revue-de-presse.api/var/llama/logs/embed.err.log   shal:staff 644  7     *    @T03 J
